/* eslint-disable */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate it.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.internal = exports.api = void 0;

const server_1 = require("convex/server");

/**
 * Placeholder API object. Functions are resolved at runtime by the Convex client.
 * Run `npx convex dev` to generate the full typed version.
 */
exports.api = (0, server_1.anyApi)();
exports.internal = (0, server_1.anyApi)();
