/* eslint-disable */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate it.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });

const {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
  internalActionGeneric,
  httpActionGeneric,
} = require("convex/server");

exports.query = queryGeneric;
exports.mutation = mutationGeneric;
exports.action = actionGeneric;
exports.internalQuery = internalQueryGeneric;
exports.internalMutation = internalMutationGeneric;
exports.internalAction = internalActionGeneric;
exports.httpAction = httpActionGeneric;
